/**
 * 2025-2026-o'quv yili uchun tayanch o'quv reja (Uzbek schools)
 * Based on 1-ILOVA
 */
export const UZBEK_CURRICULUM: Record<string, Record<string, number>> = {
  "1": {
    "Ona tili": 4,
    "O'qish savodxonligi": 4,
    "Chet tili": 1,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 1,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 1
  },
  "2": {
    "Ona tili": 4,
    "O'qish savodxonligi": 3,
    "Rus tili": 2,
    "Chet tili": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 1,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "3": {
    "Ona tili": 4,
    "O'qish savodxonligi": 3,
    "Rus tili": 2,
    "Chet tili": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 1,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "4": {
    "Ona tili": 4,
    "O'qish savodxonligi": 3,
    "Rus tili": 2,
    "Chet tili": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Tabiiy fanlar (Science)": 2,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "5": {
    "Ona tili": 4,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 4,
    "Tarixdan hikoyalar": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 2,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 2,
    "Jismoniy tarbiya": 2
  },
  "6": {
    "Ona tili": 4,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 4,
    "Qadimgi dunyo tarixi": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 3,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 2,
    "Jismoniy tarbiya": 2
  },
  "7": {
    "Ona tili": 3,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 4,
    "O'zbekiston tarixi": 2,
    "Jahon tarixi": 1,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 2,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Chizmachilik": 1,
    "Texnologiya": 2,
    "Jismoniy tarbiya": 2
  },
  "8": {
    "Ona tili": 3,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 3,
    "O'zbekiston tarixi": 2,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 1,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 1.5,
    "Iqtisodiy bilim asoslari": 0.5,
    "Chizmachilik": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "9": {
    "Ona tili": 3,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 3,
    "O'zbekiston tarixi": 2,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 1,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 1.5,
    "Iqtisodiy bilim asoslari": 0.5,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "10": {
    "Ona tili": 2,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 2,
    "O'zbekiston tarixi": 1,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 2,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 2,
    "Tadbirkorlik asoslari": 1,
    "Jismoniy tarbiya": 2,
    "Chaqiruvga qadar boshlang'ich tayyorgarlik": 2
  },
  "11": {
    "Ona tili": 2,
    "Adabiyot": 2,
    "Rus tili": 2,
    "Chet tili": 2,
    "O'zbekiston tarixi": 1,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 2,
    "Fizika": 2,
    "Astronomiya": 1,
    "Kimyo": 2,
    "Biologiya": 2,
    "Jismoniy tarbiya": 2,
    "Chaqiruvga qadar boshlang'ich tayyorgarlik": 2
  }
};

/**
 * 2025-2026-o'quv yili uchun tayanch o'quv reja (Russian schools)
 * Based on 2-ILOVA
 */
export const RUSSIAN_CURRICULUM: Record<string, Record<string, number>> = {
  "1": {
    "Ona tili": 4,
    "O'qish savodxonligi": 4,
    "Chet tili": 1,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 1,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 1
  },
  "2": {
    "Ona tili": 4,
    "O'qish savodxonligi": 3,
    "O'zbek tili": 2,
    "Chet tili": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 1,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "3": {
    "Ona tili": 4,
    "O'qish savodxonligi": 3,
    "O'zbek tili": 2,
    "Chet tili": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 1,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "4": {
    "Ona tili": 4,
    "O'qish savodxonligi": 3,
    "O'zbek tili": 2,
    "Chet tili": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Tabiiy fanlar (Science)": 2,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "5": {
    "Ona tili": 3,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 4,
    "Tarixdan hikoyalar": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 2,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 2,
    "Jismoniy tarbiya": 2
  },
  "6": {
    "Ona tili": 3,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 4,
    "Qadimgi dunyo tarixi": 2,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Tabiiy fanlar (Science)": 3,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Texnologiya": 2,
    "Jismoniy tarbiya": 2
  },
  "7": {
    "Ona tili": 2,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 4,
    "O'zbekiston tarixi": 2,
    "Jahon tarixi": 1,
    "Tarbiya": 1,
    "Matematika": 5,
    "Informatika va axborot texnologiyalari": 1,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 2,
    "Musiqa madaniyati": 1,
    "Tasviriy san'at": 1,
    "Chizmachilik": 1,
    "Texnologiya": 2,
    "Jismoniy tarbiya": 2
  },
  "8": {
    "Ona tili": 2,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 3,
    "O'zbekiston tarixi": 2,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 1,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 1.5,
    "Iqtisodiy bilim asoslari": 0.5,
    "Chizmachilik": 1,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "9": {
    "Ona tili": 2,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 3,
    "O'zbekiston tarixi": 2,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 1,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 1.5,
    "Iqtisodiy bilim asoslari": 0.5,
    "Texnologiya": 1,
    "Jismoniy tarbiya": 2
  },
  "10": {
    "Ona tili": 1,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 2,
    "O'zbekiston tarixi": 1,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 2,
    "Fizika": 2,
    "Kimyo": 2,
    "Biologiya": 2,
    "Geografiya": 2,
    "Tadbirkorlik asoslari": 1,
    "Jismoniy tarbiya": 2,
    "Chaqiruvga qadar boshlang'ich tayyorgarlik": 2
  },
  "11": {
    "Ona tili": 1,
    "Adabiyot": 2,
    "O'zbek tili": 3,
    "Chet tili": 2,
    "O'zbekiston tarixi": 1,
    "Jahon tarixi": 1,
    "Davlat va huquq asoslari": 1,
    "Tarbiya": 1,
    "Algebra": 3,
    "Geometriya": 2,
    "Informatika va axborot texnologiyalari": 2,
    "Fizika": 2,
    "Astronomiya": 1,
    "Kimyo": 2,
    "Biologiya": 2,
    "Jismoniy tarbiya": 2,
    "Chaqiruvga qadar boshlang'ich tayyorgarlik": 2
  }
};

